spring.application.name=User-Module
server.servlet.context-path=/api-user
#=============================================================================================
# MYSQL
#=============================================================================================

spring.datasource.url=jdbc:mysql://localhost:3306/user-module
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#==============================================================================================
# JPA
#==============================================================================================

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

#==============================================================================================
# FLYWAY
#==============================================================================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#==============================================================================================
# JWT
#==============================================================================================

jwt.secret=amitkijaanshaifuhaiaurshaifukijaanamithaidonoekdusrekopyarkarthe
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

#==============================================================================================
# MAIL
#==============================================================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amitrrrvaa0003@gmail.com
spring.mail.password=zpqqecwjxladtsal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#==============================================================================================
# AES EMAIL ENCRYPTION
#==============================================================================================

aes.secret-key=amitkijaanshaifuhaiaurshaifukija
